Repository dot-team/petpisode, pull requests merged in 2025-02, with the labels that each got.

#73 PET-85 [design] 공통 컴포넌트 색상 적용
  src/components/common/Button/Button.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Select/Select.tsx
  src/components/common/Textarea/Textarea.tsx
Labels: design

#72 PET-82 [design] 사용자사이트 레이아웃 마크업
  components.json
  src/app/(user)/layout.tsx
  src/app/layout.tsx
  src/components/common/index.ts
  src/components/index.ts
  src/components/layout/Header/UserHeader.tsx
  src/components/ui/checkbox.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: design

#69 PET-80 [design] 커뮤니티 부분 글 작성 card 및 콘텐츠 요소 card 마크업
  package-lock.json
  package.json
  public/images/bookmark.svg
  public/images/comment.svg
  public/images/img_upload.svg
  public/images/like.svg
  public/images/share.svg
  public/images/test.svg
  public/images/user.svg
  src/app/(user)/community/page.tsx
  src/components/common/Button/Button.tsx
  src/components/layout/PostListCard/PostListCard.tsx
  src/components/layout/Postcard/PostFormCard.tsx
  tailwind.config.js
Labels: design

#64 PET-74 [feature] 뉴스레터 본문 재구성 기능 구현
  package-lock.json
  package.json
  src/app/admin/page.tsx
  src/app/api/reconstruct-contents/route.ts
  src/app/layout.tsx
  src/components/DynamicDataTable.tsx
  src/components/ui/page.tsx
  src/constants/apis.ts
  src/constants/endpoints.ts
  src/constants/index.ts
  src/providers/Providers.tsx
  src/providers/tanstackQuery/QueryClientProvider.tsx
  src/providers/tanstackQuery/queryClient.ts
  src/services/gemini.ts
  src/services/index.ts
  src/types/apis.ts
  src/types/index.ts
Labels: feature

#77 PET-88 [design] 상세 커뮤니티 페이지 마크업
  public/images/commentIcon.svg
  public/images/test1.svg
  src/app/(user)/community/[id]/page.tsx
Labels: design

#79 refact: package.lock.json 병합 충돌 해결
  package-lock.json
Labels: refact

#80 PET-81 [feature] supabase crud 기능 추상화
  src/apis/index.ts
  src/app/admin/test/page.tsx
  src/app/api/[table]/[id]/route.ts
  src/app/api/[table]/route.ts
  src/constants/endpoints.ts
  src/lib/index.ts
  src/lib/supabase/supabase.ts
  src/services/index.ts
  src/services/supabaseClientCrud.ts
  src/services/supabaseServerCrud.ts
  src/types/index.ts
  src/types/supabaseCrudTypes.ts
  src/types/supabaseTypes.ts
  supabase.js
Labels: feature

#84 design: 아이콘 루시드 아이콘 변경 및 layout에 맞게 위치 수정
  package-lock.json
  public/images/bookmark.svg
  public/images/comment.svg
  public/images/commentIcon.svg
  public/images/img_upload.svg
  public/images/like.svg
  public/images/share.svg
  public/images/user.svg
  src/app/(user)/community/[id]/page.tsx
  src/components/layout/PostListCard/PostListCard.tsx
  src/components/layout/Postcard/PostFormCard.tsx
Labels: design

#81 PET-87 [design] 관리자 뉴스레터 수집 페이지 마크업
  src/app/admin/layout.tsx
  src/app/admin/newsletter/collect/page.tsx
  src/components/admin/AdminNewletterCollectTable.tsx
  src/components/admin/AdminSidebar.tsx
  src/components/common/Table/Table.tsx
Labels: design

#90 PET-92 [feature] 이메일 회원가입 기능 구현
  package-lock.json
  package.json
  src/app/(auth)/signup/page.tsx
  src/app/auth/confirm/route.ts
  src/app/layout.tsx
  src/components/auth/SignUpForm/SignUpForm.tsx
  src/components/auth/index.ts
  src/components/common/Form/Form.tsx
  src/components/common/Form/FormControl.tsx
  src/components/common/Form/FormDescription.tsx
  src/components/common/Form/FormField.tsx
  src/components/common/Form/FormItem.tsx
  src/components/common/Form/FormLabel.tsx
  src/components/common/Form/FormMessage.tsx
  src/components/common/Form/index.ts
  src/components/common/Toast/Toaster.tsx
  src/components/common/index.ts
  src/components/layout/Header/UserHeader.tsx
  src/hooks/index.ts
  src/hooks/useAuth.ts
  src/hooks/useErrorToast.ts
  src/hooks/useFormField.ts
  src/hooks/useSignupForm.ts
  src/hooks/useSuccessToast.ts
  src/lib/index.ts
  src/lib/supabase/actions/index.ts
  src/lib/supabase/actions/signIn.ts
  src/lib/supabase/actions/signUp.ts
  src/lib/supabase/client.ts
  src/lib/supabase/index.ts
  src/lib/supabase/server.ts
  src/lib/supabase/supabase.ts
  src/lib/supabase/supabaseRest.ts
  src/lib/supabase/utils/getSupabaseEnv.ts
  src/lib/supabase/utils/middleware.ts
  src/middleware.ts
  src/stores/index.ts
  src/stores/userStore.ts
  src/types/index.ts
  src/types/userTypes.ts
Labels: feature

#92 PET-75 [feature] 뉴스레터 발송 기능 - 웹 푸시 알림 기능 구현
  package-lock.json
  package.json
  public/service-worker.js
  src/app/api/push-notification/route.ts
  src/hooks/index.ts
  src/hooks/usePushNotification.ts
  src/types/supabaseTypes.ts
Labels: feature

#94 PET-92 [feature] 이메일 회원가입 기능 구현
  src/app/(auth)/signup/page.tsx
  src/components/auth/SignUpForm/AgreementCheckbox.tsx
  src/components/auth/SignUpForm/SignUpForm.tsx
  src/components/auth/SignUpForm/SignUpFormField.tsx
  src/components/common/Checkbox/Checkbox.tsx
  src/constants/index.ts
  src/constants/signupAgrees.ts
  src/hooks/useSignupForm.ts
  src/lib/supabase/actions/signUp.ts
Labels: feature, refact

#93 [design] 뉴스레터 조회 페이지 마크업
  src/app/(user)/newsletter/[id]/page.tsx
  src/app/(user)/newsletter/page.tsx
  src/components/admin/AdminSidebar.tsx
Labels: design

#98 PET-94 [feature] 이메일 로그인 기능 구현
  package-lock.json
  package.json
  src/app/(auth)/login/page.tsx
  src/app/layout.tsx
  src/components/auth/AuthInitializer.tsx
  src/components/auth/common/EmailLogin/EmailLogin.tsx
  src/components/auth/common/SocialLogin/SocialLogin.tsx
  src/components/auth/common/index.ts
  src/components/auth/index.ts
  src/components/auth/signin/EmailLoginForm/EmailLoginForm.tsx
  src/components/auth/signin/EmailLoginForm/LoginSubmitButton.tsx
  src/components/auth/signin/LoginButtons/LoginButtons.tsx
  src/components/auth/signin/LoginDialog/LoginDialog.tsx
  src/components/auth/signin/SignInContainer/SignInContainer.tsx
  src/components/auth/signin/index.ts
  src/components/auth/signup/SignUpForm/AgreementCheckbox.tsx
  src/components/auth/signup/SignUpForm/SignUpForm.tsx
  src/components/auth/signup/SignUpForm/SignUpFormField.tsx
  src/components/auth/signup/index.ts
  src/components/common/Form/Form.tsx
  src/components/layout/Header/AuthButtons.tsx
  src/components/layout/Header/UserHeader.tsx
  src/hooks/useAuth.ts
  src/hooks/useFormField.ts
  src/lib/supabase/actions/signIn.ts
  src/lib/supabase/actions/signUp.ts
  src/lib/supabase/utils/middleware.ts
  src/providers/Providers.tsx
  src/stores/userStore.ts
  src/types/index.ts
  src/types/loginFormTypes.ts
  src/types/userTypes.ts
Labels: feature

#96 [design] 뉴스레터 제보 페이지 마크업
  src/app/(user)/episode/page.tsx
Labels: design
