Repository dot-team/petpisode, pull requests merged in 2025-01, with the labels that each got.

#42 [Feature] develop 최신 상태로 만들기
  .github/workflows/create-iussue.yml
Labels: feature

#50 [refact] commitLint 타입 수정
  .commitlintrc.json
Labels: refact

#43 PET-62 [design] tailwind 공통 속성 설정
  src/app/globals.css
  tailwind.config.js
Labels: design

#38 [design] 공통 버튼 컴포넌트 생성
  package-lock.json
  package.json
  src/app/about/page.tsx
  src/app/page.tsx
  src/components/ui/button.tsx
Labels: design

#51 PET-51 [design] 헤더 컴포넌트 마크업
  package-lock.json
  package.json
  public/images/logo.svg
  src/app/(user)/(auth)/findpw/page.tsx
  src/app/(user)/(auth)/login/page.tsx
  src/app/(user)/(auth)/signup/page.tsx
  src/app/(user)/community/page.tsx
  src/app/(user)/episode/page.tsx
  src/app/(user)/layout.tsx
  src/app/(user)/mypage/page.tsx
  src/app/(user)/newsletter/page.tsx
  src/app/(user)/page.tsx
  src/app/Test.tsx
  src/app/admin/layout.tsx
  src/app/admin/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/publish/page.tsx
  src/components/UserHeader.tsx
  src/components/ui/avatar.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/constants/index.ts
  src/constants/navigation.ts
  src/constants/url.ts
  src/hooks/use-mobile.tsx
Labels: design

#52 PET-60 [feature] 공통 Toast 컴포넌트 추가 및 디자인 업데이트
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/Toast/Toast.tsx
  src/components/Toast/Toaster.tsx
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/useErrorToast.ts
  src/hooks/useSuccessToast.ts
  src/hooks/usetoast.ts
  src/types/common.ts
  src/types/index.ts
Labels: feature

#53 PET-57 [feature] 공통 Form 컴포넌트 추가
  package-lock.json
  package.json
  src/components/Form/Checkbox/Checkbox.tsx
  src/components/Form/Input/Input.tsx
  src/components/Form/Select/Select.tsx
  src/components/Form/Textarea/Textarea.tsx
  src/components/Form/index.ts
Labels: feature

#57 PET-53 [design] 관리자 Form 컴포넌트 마크업
  .eslintrc.json
  package-lock.json
  src/app/admin/layout.tsx
  src/app/admin/page.tsx
  src/components/admin/AdminFormContainer.tsx
  src/components/admin/AdminHeader.tsx
  src/components/admin/AdminItemBaseContainer.tsx
  src/components/admin/AdminSidebar.tsx
  src/components/admin/BreadcrumbWithCustomSeparator.tsx
  src/components/admin/index.ts
  src/components/index.ts
  src/components/ui/avatar.tsx
  src/components/ui/breadcrumb.tsx
  src/components/ui/card.tsx
  src/components/ui/index.ts
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/sidebar.tsx
Labels: design

#47 PET-56 [design] 공통 Dialog(Modal,confirm) 생성
  package-lock.json
  src/components/dialog/DialogItem.tsx
  src/components/ui/dialog.tsx
Labels: feature, design

#59 PET-77 [fix] src/components/ui/index.ts 경로 제거
  src/components/ui/index.ts
Labels: fix

#62 [File] 폴더 및 파일 이름, 구조 변경
  src/app/(user)/layout.tsx
  src/app/admin/layout.tsx
  src/app/admin/page.tsx
  src/app/layout.tsx
  src/app/publish/page.tsx
  src/components/Form/Input/Input.tsx
  src/components/Form/index.ts
  src/components/admin/AdminHeader.tsx
  src/components/admin/AdminItemBaseContainer.tsx
  src/components/admin/AdminSidebar.tsx
  src/components/admin/BreadcrumbWithCustomSeparator.tsx
  src/components/common/Avatar/Avatar.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Card/Card.tsx
  src/components/common/Checkbox/Checkbox.tsx
  src/components/common/Dialog/Dialog.tsx
  src/components/common/Dialog/DialogItem.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Label/Label.tsx
  src/components/common/Select/Select.tsx
  src/components/common/Separator/Separator.tsx
  src/components/common/Skeleton/Skeleton.tsx
  src/components/common/Textarea/Textarea.tsx
  src/components/common/Toast/Toast.tsx
  src/components/common/Toast/Toaster.tsx
  src/components/common/Tooltip/Tooltip.tsx
  src/components/common/index.ts
  src/components/index.ts
  src/components/layout/Breadcrumb/Breadcrumb.tsx
  src/components/layout/Collapsible/Collapsible.tsx
  src/components/layout/Header/UserHeader.tsx
  src/components/layout/Sheet/Sheet.tsx
  src/components/layout/Sidebar/Sidebar.tsx
  src/components/layout/index.ts
  src/components/ui/index.ts
  src/hooks/usetoast.ts
Labels: file

#68 [fix] package-lock.json 의존성 코드가 모두 두번씩 작성되어있는 문제 수정
  package-lock.json
Labels: fix

#60 PET-54 [design] 관리자 View 컴포넌트 마크업
  src/app/admin/page.tsx
  src/components/admin/AdminViewContainer.tsx
  src/components/admin/index.ts
Labels: design

#63 PET-58 [design] 관리자 데이터 테이블
  .eslintrc.json
  package-lock.json
  package.json
  src/app/admin/test/page.tsx
  src/components/DynamicDataTable.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/columns.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/page.tsx
  src/components/ui/table.tsx
Labels: design
